# Generated by Django 2.0.3 on 2018-03-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_img_small'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productbrand',
            new_name='brands',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productstore',
            new_name='stores',
        ),
    ]
