# Generated by Django 2.0.3 on 2018-03-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180319_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(db_table='products_brands', to='products.Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(db_table='products_stores', to='products.Store'),
        ),
    ]
